# Generated by Django 4.2.2 on 2023-06-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NroPlanta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Granulometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Malla500', models.CharField(max_length=50)),
                ('Malla425', models.CharField(max_length=50)),
                ('Malla300', models.CharField(max_length=50)),
                ('Malla180', models.CharField(max_length=50)),
                ('Fondo', models.CharField(max_length=50)),
                ('Planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='molienda.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Barbotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Densidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Viscosidad', models.IntegerField()),
                ('Residuo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molienda.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Atomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Codigo', models.CharField(max_length=50)),
                ('NroSilo', models.IntegerField()),
                ('Humedad', models.CharField(max_length=50)),
                ('Observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('Barbotina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='molienda.barbotina')),
                ('Granulometria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='molienda.granulometria')),
                ('Planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='molienda.planta')),
            ],
        ),
    ]
