# Generated by Django 4.2.2 on 2023-06-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('molienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomizado',
            name='Barbotina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molienda.barbotina'),
        ),
        migrations.AlterField(
            model_name='atomizado',
            name='Granulometria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molienda.granulometria'),
        ),
        migrations.AlterField(
            model_name='barbotina',
            name='Planta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='molienda.planta'),
        ),
    ]
