# Generated by Django 4.2.2 on 2023-07-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('molienda', '0004_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomizado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='molienda.usuario'),
        ),
        migrations.AddField(
            model_name='barbotina',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='molienda.usuario'),
        ),
        migrations.AddField(
            model_name='granulometria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='molienda.usuario'),
        ),
    ]
